### ISSUE TITLE
BACKGROUND

### ISSUE THREAD

**Issue by Rechravenheart** [ShainRavenheart/StitchillesCrochet.github.io#1]
Gusto ko hon yung medyo may kulay but i dont think so if alin mas okay if plain background or scenery  background with a photo of me. or wait ill crochet nalang a formal top ill wear it and u cover it there, like example much better ang cardigan right? so for now mas oky sakin yung naka terno ako na bohemian hihi hen the color ng background is likema complement sa suut ko, habang di ko pa natatapos ang cardigan hehe thenkyuuuuuuuuuuuu

**Comment by ShainRavenheart** [comment]
![image](https://github.com/ShainRavenheart/StitchillesCrochet.github.io/assets/168503555/af3c7498-4251-4837-b00a-48cd205f1071)

- Already changed the background

WILL FIX:
- will fix the rocks at the bottom by tomorrow

**Comment by Rechravenheart** [comment]
Good evening Mr. ShainRavenheart!

I am glad on how you put your efforts on this project, I am proud and
satisfied!


Rechravenheart
Stitchille's crochet Owner
Stitchille's crochet

**Comment by ShainRavenheart** [comment]
-Fixed the background already

**Comment by Rechravenheart** [comment]
Good evening Mr. Shain!

Thank you for fixing the background, I'll check it right after and then
we'll proceed for the gallery and some descriptions if possible?

Looking forward for a successful launch!

Rechille Jaraba
Owner of Stitchille's Crochet
Stitchille's crochet
